### ISSUE TITLE
Repo down?

### ISSUE THREAD

**Issue by netthier** [SvenKiljan/archlinuxarm-pbp-packages#1]
I've been having issues synchronizing for multiple days now, pacman fails with:
```
% sudo pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 alarm is up to date
 aur is up to date
 archlinuxarm-pbp.db failed to download
 privacyshark is up to date
error: failed retrieving file 'archlinuxarm-pbp.db' from pacman.kiljan.org : Failed to connect to pacman.kiljan.org port 80 after 5205 ms: Connection timed out
error: failed to synchronize all databases (download library error)
```
I also cannot access the http://kiljan.org/ domain. I tried with and without VPNs and from multiple locations.

**Comment by netthier** [comment]
Seems to be up again, weird...

**Comment by SvenKiljan** [comment]
There was an IP change of the server's connection that took more time than expected to propagate in DNS. This should have been a one-time event, and will not occur anymore in the foreseeable future. As you noted, the issue has been solved.
