### ISSUE TITLE
Building uboot-pinebookpro

### ISSUE THREAD

**Issue by jzbor** [SvenKiljan/archlinuxarm-pbp-packages#2]
Hi,
First of all thanks for your work supporting the PBP on ALARM. I am trying to build the `uboot-pinebookpro` package myself to play around with the versions and test which works best with s2ram. But your PKGBUILD for it depends on `arm-none-eabi-gcc` which is available on x86 Arch and Manjaro Arm, but not in the ALARM repos. How do you build this package? Do you just use the Manjaro package for `arm-none-eabi-gcc`?

Thanks in advance,
Julian

**Comment by sravanpannala** [comment]
I am having the same issue.

**Comment by SvenKiljan** [comment]
I built and install Arch Linux package [arm-none-eabi-gcc](https://github.com/archlinux/svntogit-community/tree/packages/arm-none-eabi-gcc/trunk) [like an AUR package](https://wiki.archlinux.org/title/Arch_User_Repository#Build_the_package) manually on a Raspberry Pi 4B. Last time I did this (not optimized) this took almost eight hours.
